# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name' : 'QRCode for Stock Picking/Transfer/Delivery Order',
    'author': 'OMAX Informatics',
    'version': '1.0',
    'website': 'https://www.omaxinformatics.com',
    'category': 'Warehouse',
    'description' : '''
        This Odoo app allows to generate QR Code based on configuration parameters for Stock Picking(Internal Transfer/Incoming Shipment/Delivery Order).
    ''',
    'depends' : ['stock'],
    'data': [
        'report/picking_operations_report.xml',
        'views/res_company_view.xml',
        'views/stock_picking_view.xml',
    ],
    'demo': [],
    'test': [],
    'images': ['static/description/banner.png',],
    'license': 'OPL-1',
    'currency':'USD',
    'price': 20.0,
    'installable' : True,
    'auto_install' : False,
    'application' : True,
    'pre_init_hook': 'pre_init_check',
    'module_type': 'official',
    'summary': '''
        Picking QR Code,
        Delivery Order QR Code,
        Stock Picking QR Code,
        DO QR Code,
        Internal Transfer QR Code,
        Transfer QR Code,
        Stock QR Code,
        Incoming Shipment QR Code,
        Shipment QR Code,
        Picking QRCode,
        Delivery Order QRCode,
        Stock Picking QRCode,
        DO QRCode,
        Internal Transfer QRCode,
        Transfer QRCode,
        Stock QRCode,
        Incoming Shipment QRCode,
        Shipment QRCode,
        Picking Barcode,
        Delivery Order Barcode,
        Stock Picking Barcode,
        DO Barcode,
        Internal Transfer Barcode,
        Transfer Barcode,
        Stock Barcode,
        QRCode,
        QR Code,
        Barcode,
        Generate QR Code,
        Generate QR Code for Picking,
        Generate Barcode,
        Generate QRcode for Picking,
        Generate QRcode for Delivery Order,
        Generate QRcode for DO,
        Generate QRcode for Internal Transfer,
        Generate QRcode for Incoming Shipment,
        Picking QR Code Generator,
        Scan QR Code,
        Scan Barcode Generator,
        Scan Barcode,
        Mobile QR Code Scan,
	''',
}

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
